export type { BlockParseType, InlineParseType, ClosedParseType } from './config/dom-parse'
export type { NodePatchResultType } from './config/format-patch'
export type { RuleFunctionType } from './config/format-rules'
export type { EditorConfigureOptionType, EditorSelectedType } from './Editor'
export type { HistoryRecordType } from './History'
export type { KNodeCreateOptionType, KNodeMarksType, KNodeStylesType, KNodeType, ZeroWidthTextKNodeCreateOptionType } from './KNode'
export type { SelectionPointType } from './Selection'

export { Editor } from './Editor'
export { History } from './History'
export { KNode } from './KNode'
export { Selection } from './Selection'
