export { AlexEditor as default, AlexEditor } from './Editor';
export { AlexElement } from './Element';
export { AlexHistory } from './History';
export { AlexPoint } from './Point';
export { AlexRange } from './Range';
export type * from './Editor';
export type * from './Element';
export type * from './History';
export type * from './core/tool';
export type * from './core/nodeParse';
export declare const version = "1.4.26";
